# Generated by Django 2.1.3 on 2018-12-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20181202_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='catalog.OrderProducts', to='catalog.Product'),
        ),
    ]
